#!/usr/bin/env python3
from pathlib import Path

from tasklib.paths import TaskError, find_main_root, task_dir, utc_now
from tasklib.state import apply_transition, board_lock, commit_on_main, read_status


THREAD_HEAD = "# Thread {task}\n\nAppend-only. Write with `scripts/task say`.\n"


def read_title(main_root, task):
    brief = task_dir(main_root, task) / "brief.md"
    if not brief.exists():
        raise TaskError(f"task {task} is not on the board")
    rows = brief.read_text(encoding="utf-8").splitlines()
    if not rows:
        return task
    first = rows[0].strip()
    if ":" in first:
        return first.split(":", 1)[1].strip()
    return first[2:].strip() if first.startswith("# ") else first


def list_board_rows(main_root):
    base = main_root / "docs" / "tasks"
    rows = []
    if not base.exists():
        return rows
    for entry in sorted(base.iterdir(), key=lambda item: item.name):
        if not entry.is_dir():
            continue
        if not (entry / "brief.md").exists() or not (entry / "status").exists():
            continue
        seen = read_status(entry, entry.name)
        rows.append(
            (entry.name, read_title(main_root, entry.name), seen.state, seen.owner, seen.since)
        )
    return rows


def render_board(rows, stamp):
    lines = [
        "# Task board (generated by `scripts/task board`; do not edit by hand)",
        "",
        "Generated "
        + stamp
        + ". States: open \u2192 claimed \u21c4 blocked \u2192 submitted \u2192 accepted | changes-requested.",
        "",
        "| Task | Title | State | Owner | Since (UTC) |",
        "|---|---|---|---|---|",
    ]
    for task, title, state, owner, since in rows:
        if state == "open":
            owner, since = "-", "-"
        lines.append(f"| {task} | {title} | {state} | {owner} | {since} |")
    return "\n".join(lines) + "\n"


def write_board(main_root):
    text = render_board(list_board_rows(main_root), utc_now())
    (main_root / "docs" / "tasks" / "BOARD.md").write_text(text, encoding="utf-8")


def append_thread_entry(main_root, task, stamp, author, kind, message):
    thread = task_dir(main_root, task) / "thread.md"
    if not thread.exists():
        thread.write_text(THREAD_HEAD.format(task=task), encoding="utf-8")
    with open(thread, "a", encoding="utf-8") as stream:
        stream.write(f"\n### {stamp} \u00b7 {author} \u00b7 {kind}\n\n{message}\n")


def say_task(task, kind, message, identity):
    main_root = find_main_root(Path.cwd())
    with board_lock(main_root):
        packet = task_dir(main_root, task)
        if not (packet / "brief.md").exists():
            raise TaskError(f"task {task} is not on the board")
        touched = [f"docs/tasks/{task}/thread.md"]
        append_thread_entry(main_root, task, utc_now(), identity, kind, message)
        if kind == "QUESTION":
            apply_transition(packet, task, "block", identity)
            touched.append(f"docs/tasks/{task}/status")
        elif kind == "ANSWER" and read_status(packet, task).state == "blocked":
            apply_transition(packet, task, "unblock", identity)
            touched.append(f"docs/tasks/{task}/status")
        write_board(main_root)
        touched.append("docs/tasks/BOARD.md")
        commit_on_main(main_root, touched, f"{task}: {kind} from {identity}")


def review_task(task, decision, message, identity):
    main_root = find_main_root(Path.cwd())
    with board_lock(main_root):
        packet = task_dir(main_root, task)
        if not (packet / "brief.md").exists():
            raise TaskError(f"task {task} is not on the board")
        first = "ACCEPTED" if decision == "accept" else "CHANGES REQUESTED"
        append_thread_entry(main_root, task, utc_now(), identity, "REVIEW", f"{first}\n{message}")
        action = "accept" if decision == "accept" else "request-changes"
        apply_transition(packet, task, action, identity)
        write_board(main_root)
        commit_on_main(
            main_root,
            [f"docs/tasks/{task}/thread.md", f"docs/tasks/{task}/status", "docs/tasks/BOARD.md"],
            f"{task}: REVIEW from {identity}",
        )


def release_task(task, reason, identity):
    main_root = find_main_root(Path.cwd())
    with board_lock(main_root):
        packet = task_dir(main_root, task)
        if not (packet / "brief.md").exists():
            raise TaskError(f"task {task} is not on the board")
        append_thread_entry(main_root, task, utc_now(), identity, "NOTE", reason)
        apply_transition(packet, task, "release", identity)
        write_board(main_root)
        commit_on_main(
            main_root,
            [f"docs/tasks/{task}/thread.md", f"docs/tasks/{task}/status", "docs/tasks/BOARD.md"],
            f"{task}: released by {identity}",
        )


def refresh_board():
    main_root = find_main_root(Path.cwd())
    with board_lock(main_root):
        marker = main_root / "docs" / "tasks" / "BOARD.md"
        before = marker.read_text(encoding="utf-8") if marker.exists() else ""
        write_board(main_root)
        if marker.read_text(encoding="utf-8") != before:
            commit_on_main(main_root, ["docs/tasks/BOARD.md"], "board: regenerate")
