#!/usr/bin/env python3
import re

from conftest import OWNER, TASK, read_status, run_git, run_task, worktree_of

UTC = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"


def test_list_shows_open(task_repo):
    done = run_task(task_repo, "list")
    assert done.returncode == 0, done.stderr
    assert f"{TASK}  open" in done.stdout


def test_claim_writes_status_and_worktree(task_repo):
    done = run_task(task_repo, "claim", TASK, "--as", OWNER)
    assert done.returncode == 0, done.stderr
    assert re.fullmatch(f"claimed {OWNER} {UTC}", read_status(task_repo, TASK))
    assert "task/T-900" in run_git(task_repo, "branch", "--list", "task/T-900")
    assert worktree_of(task_repo, TASK).is_dir()
    assert "claimed by" in run_git(task_repo, "log", "--oneline", "-1")


def test_second_claim_fails(task_repo, claimed_repo):
    done = run_task(task_repo, "claim", TASK, "--as", "other@codex")
    assert done.returncode == 1
    assert f"error: cannot claim {TASK}: it is 'claimed'" in done.stderr


def test_say_question_blocks_and_answer_unblocks(claimed_repo):
    root = claimed_repo
    asked = run_task(root, "say", TASK, "QUESTION", "which backend?", "--as", OWNER)
    assert asked.returncode == 0, asked.stderr
    assert read_status(root, TASK).startswith("blocked ")
    thread = (root / "docs" / "tasks" / TASK / "thread.md").read_text(encoding="utf-8")
    assert thread.startswith("# Thread T-900")
    assert f" \u00b7 {OWNER} \u00b7 QUESTION" in thread
    assert "which backend?" in thread
    answered = run_task(root, "say", TASK, "ANSWER", "use mock", "--as", OWNER)
    assert answered.returncode == 0, answered.stderr
    assert read_status(root, TASK).startswith("claimed ")


def test_board_has_header_and_row(claimed_repo):
    board = (claimed_repo / "docs" / "tasks" / "BOARD.md").read_text(encoding="utf-8")
    assert board.startswith("# Task board (generated by `scripts/task board`; do not edit by hand)")
    assert "| Task | Title | State | Owner | Since (UTC) |" in board
    assert f"| {TASK} | throwaway fixture task | claimed | {OWNER} |" in board


def test_show_prints_brief_status_thread(claimed_repo):
    run_task(claimed_repo, "say", TASK, "NOTE", "hello", "--as", OWNER)
    done = run_task(claimed_repo, "show", TASK)
    assert done.returncode == 0, done.stderr
    assert "brief.md" in done.stdout
    assert "claimed" in done.stdout
    assert "hello" in done.stdout
