// Film-editing voice: short, concrete, sentence case.
export const sequenceCopy = {
  header: {
    title: "Sequence",
    body: "Cut two to six shots into one film. Add a shot, trim it, then render.",
  },
  steps: {
    add: {
      number: "1",
      heading: "Add videos",
      body: "Pick finished clips below. Need one first? Make it in Clip.",
    },
    arrange: {
      number: "2",
      heading: "Arrange & trim",
      body: "Drag to reorder. Trim the start and end in seconds.",
    },
    music: {
      number: "3",
      heading: "Music (optional)",
      body: "Drop a track, or leave it silent.",
    },
    render: {
      number: "4",
      heading: "Render & export",
      body: "Render the film, then download, share, or face-swap it.",
    },
  },
  timeline: {
    title: "Your film",
    hint: "Drag a shot to reorder, trim its ends, or swap a face.",
  },
  strip: {
    emptySlot: "Add a shot",
    emptyHint: "Add at least two shots to render.",
    removeShot: (position: number) => `Remove shot ${position}`,
    moveLeft: (position: number) => `Move shot ${position} left`,
    moveRight: (position: number) => `Move shot ${position} right`,
    faceSwap: (position: number) => `Face swap shot ${position}`,
    shotLabel: (position: number, total: number) => `Shot ${position} of ${total}`,
    swapped: "Swapped",
    clip: "Clip",
  },
  trim: {
    stepNote: "Each tap moves 0.5 seconds.",
    startEarlier: (position: number) => `Shot ${position}: move the start 0.5 seconds earlier`,
    startLater: (position: number) => `Shot ${position}: move the start 0.5 seconds later`,
    endEarlier: (position: number) => `Shot ${position}: move the end 0.5 seconds earlier`,
    endLater: (position: number) => `Shot ${position}: move the end 0.5 seconds later`,
  },
  transitions: {
    cut: { label: "CUT", name: "Cut" },
    crossfade: { label: "XFADE", name: "Crossfade" },
    fade_black: { label: "FADE", name: "Fade to black" },
  },
  picker: {
    heading: "Add a shot",
    add: "Add",
    added: "Added",
    differentShape: (ratio: string) => `Different shape: ${ratio}`,
    hint: "Finished clips from your rail. A face-swapped video works here too.",
    emptyTitle: "No finished clips yet",
    emptyBody: "Make a clip in Clip, or swap a face into a video in Face swap.",
    goToClip: "Go to Clip",
    goToFaceSwap: "Go to Face swap",
    fullTitle: "Sequence is full",
    fullBody: "Six shots is the limit. Remove one to add another.",
    faceSwapHint: "Want a different face in a shot? Swap it first, then add the result.",
  },
  music: {
    heading: "Music (optional)",
    hint: "Drop an mp3, m4a or wav here, up to 10 MB.",
    silent: "Silent. Clip audio is not used.",
    remove: "Remove music",
    browse: "Choose a file",
  },
  total: {
    label: "about",
  },
  render: {
    button: "Render · 1 credit",
    needTwoClips: "Add one more shot to render.",
    uploading: "Wait for the music to finish uploading.",
    clipInvalid: "One of these shots can't be used any more. Remove it and try again.",
    limit: "That's today's job limit. It resets at midnight UTC.",
    failed: "The render didn't start. Try again.",
  },
  exportGuide: {
    heading: "Your film is rendering",
    started: "It lands on the stage and in your rail when it's done.",
    download: "Download the mp4 from the stage or the rail.",
    share: "Share it with a link:",
    faceswap: "To change a face, open the film and use it as a face swap target.",
  },
} as const
