const sessionError = "Couldn't start a session. Try again."
const missingGeneration = "This generation isn't available anymore."

const statusLabels = {
  queued: "Queued",
  generating: "Generating",
  done: "Done",
  failed: "Failed",
} as const

export const createVideoCopy = {
  page: {
    title: "Create video",
    appTitle: "Higgsfield",
    documentTitle: "Create video · Higgsfield",
    imageSection: "Image",
    presetSection: "Preset",
    promptSection: "Prompt",
  },
  image: {
    idleTitle: "Add an image",
    idleBody: "Drop it here, browse, or paste from your clipboard.",
    browse: "Browse files",
    hint: "PNG, JPG or WebP up to 10 MB",
    draggingTitle: "Drop to upload",
    uploading: (pct: number) => `Uploading… ${pct}%`,
    replace: "Replace",
    remove: "Remove image",
    alt: "Your image",
    retry: "Try again",
    networkError: "Upload failed. Check your connection and try again.",
    sessionError,
    notFinishedError: "Upload didn't finish. Try again.",
  },
  preset: {
    categoriesLabel: "Preset categories",
    categories: {
      all: "All",
      camera: "Camera",
      cinematic: "Cinematic",
      dynamic: "Dynamic",
    },
    loading: "Loading presets…",
    emptyList: "No presets available right now.",
    emptyFilter: "No presets in this category.",
    errorInline: "Presets didn't load.",
    errorToast: "Couldn't load presets.",
    unknownSlug: "That preset isn't available. Pick another one.",
    descriptionIdle: "Pick a camera move for your video.",
    description: (name: string, description: string) => `${name}: ${description}`,
  },
  prompt: {
    label: "Prompt",
    optional: "Optional",
    placeholder: "Describe the mood or motion, e.g. “foggy morning, slow and calm”",
    counter: (length: number) => `${length}/500`,
    helper: "Some presets ignore the prompt.",
  },
  generate: {
    label: "Generate",
    withCost: (cost: number) => `Generate · ${cost} credits`,
    submitting: "Starting…",
    blockedNoImageNoPreset: "Add an image and pick a preset to generate.",
    blockedNoImage: "Add an image to generate.",
    blockedNoPreset: "Pick a preset to generate.",
    blockedUploading: "Wait for the upload to finish.",
    balanceKnown: (balance: number) => `Balance: ${balance} credits`,
    balanceLoading: "Balance: …",
    balanceError: "Balance unavailable",
    guestOffer: "Free credits to start. No sign-up needed.",
    getCredits: "Get credits",
    insufficient: (balance: number, required: number) =>
      `You have ${balance} credits. This video needs ${required}.`,
    inputMissing: "That image is no longer available. Add it again.",
    inputNotReady: "Your image is still uploading. Try again in a moment.",
    sessionError,
    invalid: "Something went wrong. Try again.",
    networkToast: "Couldn't reach the server.",
  },
  howItWorks: {
    heading: "Make a video in three steps",
    sub: "Add a photo, pick a camera move and press Generate. Your video is ready in about a minute.",
    step1Title: "Add image",
    step1Body: "Drop, browse or paste a photo.",
    step2Title: "Pick a preset",
    step2Body: (presetCount: number) =>
      presetCount === 0 ? "Choose a camera move." : `Choose one of ${presetCount} camera moves.`,
    step3Title: "Generate",
    step3Body: "Get a 5-second video to download and share.",
    imageAlt: "Your uploaded reference photo",
    badgeDone: "Done",
    badgeUploading: "Uploading…",
  },
  progress: {
    submittingHeading: "Starting…",
    submittingSub: "Sending your job.",
    queuedHeading: statusLabels.queued,
    queuedSub: "Waiting for a free worker…",
    requeuedSub: "Retrying on another worker…",
    generatingHeading: statusLabels.generating,
    generatingSub: "Animating your image. This usually takes under a minute.",
    barLabel: "Generating video",
    elapsed: (formatted: string) => `${formatted} elapsed`,
    polling: "Live updates paused. Checking every 5 seconds.",
  },
  result: {
    heading: "Your video is ready",
    meta: (presetName: string, formatted: string) => `${presetName} · done in ${formatted}`,
    download: "Download",
    downloading: "Downloading…",
    makeAnother: "Make another",
    share: "Share",
    linkCopied: "Link copied",
    openSharePage: "Open share page",
  },
  failure: {
    heading: "Generation failed",
    refunded: (creditCost: number) =>
      `Generation failed — your ${creditCost} credits were refunded`,
    missingHeading: "Not available",
    missingBody: missingGeneration,
    backToCreate: "Back to create",
  },
  history: {
    label: "This session",
    tile: (presetName: string, statusLabel: string) => `Open ${presetName}, ${statusLabel}`,
  },
  status: statusLabels,
  announce: {
    uploading: "Uploading image",
    uploaded: "Image uploaded",
    starting: "Starting generation",
    queued: "Generation queued",
    generating: "Generating video",
    ready: "Video ready",
    failed: (creditCost: number) =>
      `Generation failed. Your ${creditCost} credits were refunded.`,
    missing: missingGeneration,
  },
  toast: {
    retry: "Retry",
    dismiss: "Dismiss",
  },
} as const
