const sessionError = "Couldn't start a session. Try again."

export const createVideoCopy = {
  page: {
    title: "Animate a still",
    imageSection: "Image",
    presetSection: "Motion preset",
    promptSection: "Prompt",
    seededLabel: "From your still",
    seededRemove: "Start from another image",
  },
  image: {
    idleTitle: "Add an image",
    idleBody: "Drop it here, browse, or paste from your clipboard.",
    browse: "Browse files",
    hint: "PNG, JPG or WebP up to 10 MB",
    draggingTitle: "Drop to upload",
    uploading: (pct: number) => `Uploading… ${pct}%`,
    replace: "Replace",
    remove: "Remove image",
    alt: "Your image",
    retry: "Try again",
    networkError: "Upload failed. Check your connection and try again.",
    sessionError,
    notFinishedError: "Upload didn't finish. Try again.",
  },
  preset: {
    categoriesLabel: "Preset categories",
    categories: {
      all: "All",
      camera: "Camera",
      cinematic: "Cinematic",
      dynamic: "Dynamic",
    },
    loading: "Loading presets…",
    emptyList: "No presets available right now.",
    emptyFilter: "No presets in this category.",
    errorInline: "Presets didn't load.",
    errorToast: "Couldn't load presets.",
    unknownSlug: "That preset isn't available. Pick another one.",
    descriptionIdle: "Pick a camera move for your clip.",
    description: (name: string, description: string) => `${name}: ${description}`,
  },
  prompt: {
    label: "Prompt",
    optional: "Optional",
    placeholder: "Describe the mood or motion, e.g. \u201cfoggy morning, slow and calm\u201d",
    counter: (length: number) => `${length}/500`,
    helper: "Some presets ignore the prompt.",
  },
  generate: {
    label: "Animate",
    withCost: (cost: number) => `Animate \u00b7 ${cost} credits`,
    submitting: "Starting…",
    blockedNoImageNoPreset: "Add an image and pick a preset to animate.",
    blockedNoImage: "Add an image to animate.",
    blockedNoPreset: "Pick a preset to animate.",
    blockedUploading: "Wait for the upload to finish.",
    balanceKnown: (balance: number) => `Balance: ${balance} credits`,
    balanceLoading: "Balance: …",
    balanceError: "Balance unavailable",
    guestOffer: "Free credits to start. No sign-up needed.",
    insufficient: (balance: number, required: number) =>
      `You have ${balance} credits. This clip needs ${required}.`,
    inputMissing: "That image is no longer available. Add it again.",
    inputNotReady: "Your image is still uploading. Try again in a moment.",
    sessionError,
    invalid: "That didn't go through. Try again.",
    networkToast: "Couldn't reach the server.",
    limitHit: "That's today's job limit. It resets at midnight UTC.",
    creditsOpened: "Not enough credits — the credits panel is open.",
  },
  toast: {
    retry: "Retry",
    dismiss: "Dismiss",
  },
} as const
