// T-030: every showcase asset is our own, generated by scripts/build-preset-previews.
export const R2_PUBLIC_BASE = "https://pub-e14a8ad582a945a7a46dd46e2b138ec2.r2.dev"

export function previewClipUrl(slug: string): string {
  return `${R2_PUBLIC_BASE}/previews/${slug}.mp4`
}

// scripts/build-preset-previews uploads a poster JPG next to every preview mp4, same key stem.
export function previewPosterUrl(mediaUrl: string): string | null {
  return mediaUrl.endsWith(".mp4") ? `${mediaUrl.slice(0, -4)}.jpg` : null
}

export const SHOWCASE_MEDIA = {
  dollyIn: { title: "DOLLY IN", tag: "CAMERA MOVE", slug: "dolly-in" },
  dollyOutSlug: "dolly-out",
  panLeftSlug: "pan-left",
  orbitPush: { title: "ORBIT PUSH", tag: "CINEMATIC", slug: "orbit-push" },
  crashZoom: { title: "CRASH ZOOM", tag: "DYNAMIC", slug: "crash-zoom" },
  kenBurns: { title: "KEN BURNS", tag: "DOCUMENTARY", slug: "ken-burns" },
} as const

// Real FLUX.1-schnell generations (apps/gpu/flux_image.py); see docs/research/preview-sources.md.
export const SHOWCASE_STILLS = [
  { title: "NEON ALLEY", url: "/showcase/sample-01.jpg", aspect: "IMAGE" },
  { title: "DESERT CANYON", url: "/showcase/sample-02.jpg", aspect: "IMAGE" },
  { title: "PORTRAIT", url: "/showcase/sample-03.jpg", aspect: "IMAGE" },
  { title: "FOREST PATH", url: "/showcase/sample-04.jpg", aspect: "IMAGE" },
] as const

// T1 (012): old R2 image-1.png stills resolved but looked near-identical,
// so stills use distinct local samples and clips use R2 previews.
type ShowcaseItem = { url: string; poster: string | null; caption: string }

const dollyInUrl = previewClipUrl(SHOWCASE_MEDIA.dollyIn.slug)
const orbitPushUrl = previewClipUrl(SHOWCASE_MEDIA.orbitPush.slug)

export const SHOWCASE: {
  still: ShowcaseItem
  clip: ShowcaseItem
  faceswap: ShowcaseItem
  sequence: ShowcaseItem
  orbitClip: ShowcaseItem
  canyonStill: ShowcaseItem
} = {
  still: {
    url: "/showcase/sample-01.jpg",
    poster: null,
    caption: "Still — prompt → picture",
  },
  clip: {
    url: dollyInUrl,
    poster: previewPosterUrl(dollyInUrl),
    caption: "Clip — still + motion preset, 0:05",
  },
  faceswap: {
    url: "/showcase/sample-03.jpg",
    poster: null,
    caption: "Face swap — face + target photo",
  },
  sequence: {
    url: "https://pub-e14a8ad582a945a7a46dd46e2b138ec2.r2.dev/users/62fc7a93-fbfc-49a6-a228-05a5c6184337/jobs/42e05b9f-08be-4876-bdce-1cac0b608ab5/video.mp4",
    poster:
      "https://pub-e14a8ad582a945a7a46dd46e2b138ec2.r2.dev/users/62fc7a93-fbfc-49a6-a228-05a5c6184337/jobs/42e05b9f-08be-4876-bdce-1cac0b608ab5/poster.jpg",
    caption: "Sequence — 2 shots cut to 0:07",
  },
  orbitClip: {
    url: orbitPushUrl,
    poster: previewPosterUrl(orbitPushUrl),
    caption: "Clip — orbit push preset, 0:05",
  },
  canyonStill: {
    url: "/showcase/sample-02.jpg",
    poster: null,
    caption: "Still — landscape prompt → picture",
  },
}
